version: "3"
services: 
  elasticsearch:
    container_name: elasticsearch
    build: env/elasticsearch
    environment: 
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    command: /usr/share/elasticsearch/bin/elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    links: 
      - elasticsearch
    ports: 
      - 5601:5601
  
  etl:
    container_name: etl
    build: etl
    depends_on: 
      - elasticsearch
    volumes: 
      - ./etl:/app/src
      - ./lib:/app/src/lib
      - ./data/text:/app/text
    
  web:
    container_name: web
    build: web
    depends_on: 
      - elasticsearch
    volumes: 
      - ./web:/app/src
      - ./lib:/app/src/lib
    ports: 
      - 8501:8501
    command: streamlit run main.py 

  jupyter:
    container_name: jupyter
    build: jupyter
    depends_on: 
      - elasticsearch
    volumes: 
      - ./jupyter:/app/src
      - ./lib:/app/src/notebook/lib
      - ./data/text:/app/text
    ports: 
      - 8888:8888
    command: jupyter-notebook --ip="0.0.0.0" --allow-root

